// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9");

            modelBuilder.Entity("API.Entities.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2020, 11, 3, 10, 27, 6, 406, DateTimeKind.Local).AddTicks(943),
                            Description = "Task1",
                            IsDone = false
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2020, 11, 3, 10, 27, 6, 412, DateTimeKind.Local).AddTicks(6704),
                            Description = "Task2",
                            IsDone = false
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2020, 11, 3, 10, 27, 6, 412, DateTimeKind.Local).AddTicks(6781),
                            Description = "Task3",
                            IsDone = false
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2020, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "TAsk4",
                            IsDone = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
